POST {{baseUrl}}/api/v1/courses HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "identification": "Redes",
    "coordinatorId": 1,
    "classRoomIds": [
        
    ]
}

###

GET {{baseUrl}}/api/v1/courses HTTP/1.1
Authorization: Bearer {{token}}

###

POST {{baseUrl}}/api/v1/courses/12/add-classroom HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "classRoomIds": [
        4
    ]
}

###

DELETE  {{baseUrl}}/api/v1/courses/2/remove-classroom HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "classRoomIds": [
        4,
        6
    ]
}